version: '3.9'

services:
  frontend:
    image: frontendscout
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../assetchain-envs/common-frontend.env
